# Generated by Django 4.1.13 on 2024-04-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("healthdiary", "0002_bodypart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodypart",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="sports/%Y/%m/%d")),
                (
                    "bodyPart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports",
                        to="healthdiary.bodypart",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="sport",
            index=models.Index(fields=["id", "slug"], name="healthdiary_id_f8e866_idx"),
        ),
    ]
