# Generated by Django 4.1.13 on 2024-04-11 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("healthdiary", "0003_alter_bodypart_options_sport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="users_liked",
            field=models.ManyToManyField(
                related_name="sports_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
