# Generated by Django 4.1.13 on 2024-04-12 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("healthdiary", "0006_alter_sport_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sport",
            name="user",
        ),
        migrations.AddField(
            model_name="sport",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sport",
            name="createdBy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sport_createdBy",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sport",
            name="bodyPart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sport_bodyPart",
                to="healthdiary.bodypart",
            ),
        ),
    ]
