# Generated by Django 4.1.13 on 2024-04-12 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "healthdiary",
            "0007_remove_sport_user_sport_created_sport_createdby_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                ("exercise_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["-exercise_date"],
            },
        ),
        migrations.RemoveIndex(
            model_name="sport",
            name="healthdiary_id_f8e866_idx",
        ),
        migrations.AddIndex(
            model_name="sport",
            index=models.Index(
                fields=["id", "slug", "createdBy"], name="healthdiary_id_60172a_idx"
            ),
        ),
        migrations.AddField(
            model_name="sporthistory",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sport_sport_history",
                to="healthdiary.sport",
            ),
        ),
        migrations.AddField(
            model_name="sporthistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sport_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
