# Generated by Django 4.1.13 on 2024-04-11 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("healthdiary", "0004_sport_users_liked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sport",
            name="users_liked",
        ),
        migrations.AddField(
            model_name="sport",
            name="user",
            field=models.ManyToManyField(
                related_name="sport_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
