# Generated by Django 4.1.13 on 2024-04-13 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "healthdiary",
            "0008_sporthistory_remove_sport_healthdiary_id_f8e866_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sporthistory",
            options={"ordering": ["-sport_date"]},
        ),
        migrations.RenameField(
            model_name="sporthistory",
            old_name="exercise_date",
            new_name="sport_date",
        ),
    ]
